"""Compatibility bridge for privacy access policy helpers."""

from t2c_data.features.privacy_access import (
    ACCESS_ROLE_LABELS,
    ACCESS_ROLE_OPTIONS,
    ACCESS_SCOPE_LABELS,
    ACCESS_SCOPE_OPTIONS,
    LEGAL_BASIS_LABELS,
    LEGAL_BASIS_OPTIONS,
    SENSITIVITY_LABELS,
    SENSITIVITY_LEVELS,
    access_role_labels,
    access_scope_label,
    can_edit_privacy,
    can_view_table,
    default_access_scope_for_sensitivity,
    legal_basis_label,
    normalize_access_role,
    normalize_access_roles,
    privacy_change_snapshot,
    privacy_summary_payload,
    role_tokens_for_user,
    sensitivity_label,
    suggest_possible_personal_data,
)

__all__ = [
    "ACCESS_ROLE_LABELS",
    "ACCESS_ROLE_OPTIONS",
    "ACCESS_SCOPE_LABELS",
    "ACCESS_SCOPE_OPTIONS",
    "LEGAL_BASIS_LABELS",
    "LEGAL_BASIS_OPTIONS",
    "SENSITIVITY_LABELS",
    "SENSITIVITY_LEVELS",
    "access_role_labels",
    "access_scope_label",
    "can_edit_privacy",
    "can_view_table",
    "default_access_scope_for_sensitivity",
    "legal_basis_label",
    "normalize_access_role",
    "normalize_access_roles",
    "privacy_change_snapshot",
    "privacy_summary_payload",
    "role_tokens_for_user",
    "sensitivity_label",
    "suggest_possible_personal_data",
]
