"""baseline

Revision ID: 55da547ae3ae
Revises: 
Create Date: 2026-02-21 15:16:23.993927

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '55da547ae3ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('db_type', sa.String(length=20), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('include_schemas', sa.JSON(), nullable=True),
    sa.Column('exclude_schemas', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_data_sources_name'),
    schema='t2c_data'
    )
    op.create_table('glossary_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steward', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_glossary_terms_name'),
    schema='t2c_data'
    )
    op.create_table('lineage_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='t2c_data'
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_roles_name'),
    schema='t2c_data'
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_tags_name'),
    schema='t2c_data'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    schema='t2c_data'
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['t2c_data.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='t2c_data'
    )
    op.create_table('databases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description_source', sa.Text(), nullable=True),
    sa.Column('description_manual', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['t2c_data.data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datasource_id', 'name', name='uq_databases_datasource_name'),
    schema='t2c_data'
    )
    op.create_table('glossary_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['t2c_data.data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['t2c_data.glossary_terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'entity_type', 'entity_id', name='uq_glossary_assignment_entity'),
    schema='t2c_data'
    )
    op.create_index(op.f('ix_t2c_data_glossary_assignments_datasource_id'), 'glossary_assignments', ['datasource_id'], unique=False, schema='t2c_data')
    op.create_table('lineage_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=True),
    sa.Column('from_entity_type', sa.String(length=40), nullable=False),
    sa.Column('from_entity_id', sa.Integer(), nullable=False),
    sa.Column('to_entity_type', sa.String(length=40), nullable=False),
    sa.Column('to_entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['t2c_data.data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_id'], ['t2c_data.lineage_processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='t2c_data'
    )
    op.create_index(op.f('ix_t2c_data_lineage_edges_datasource_id'), 'lineage_edges', ['datasource_id'], unique=False, schema='t2c_data')
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_by', sa.Integer(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['t2c_data.data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by'], ['t2c_data.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='t2c_data'
    )
    op.create_table('tag_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['t2c_data.data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['t2c_data.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'entity_type', 'entity_id', name='uq_tag_assignment_entity'),
    schema='t2c_data'
    )
    op.create_index(op.f('ix_t2c_data_tag_assignments_datasource_id'), 'tag_assignments', ['datasource_id'], unique=False, schema='t2c_data')
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['t2c_data.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['t2c_data.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='t2c_data'
    )
    op.create_table('scan_diffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_key', sa.String(length=400), nullable=False),
    sa.Column('diff_type', sa.String(length=20), nullable=False),
    sa.Column('old_hash', sa.String(length=64), nullable=True),
    sa.Column('new_hash', sa.String(length=64), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['t2c_data.scan_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='t2c_data'
    )
    op.create_index(op.f('ix_t2c_data_scan_diffs_entity_key'), 'scan_diffs', ['entity_key'], unique=False, schema='t2c_data')
    op.create_table('scan_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_key', sa.String(length=400), nullable=False),
    sa.Column('entity_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['t2c_data.scan_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='t2c_data'
    )
    op.create_index(op.f('ix_t2c_data_scan_snapshots_entity_hash'), 'scan_snapshots', ['entity_hash'], unique=False, schema='t2c_data')
    op.create_index(op.f('ix_t2c_data_scan_snapshots_entity_key'), 'scan_snapshots', ['entity_key'], unique=False, schema='t2c_data')
    op.create_table('schemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description_source', sa.Text(), nullable=True),
    sa.Column('description_manual', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['t2c_data.databases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('database_id', 'name', name='uq_schemas_database_name'),
    schema='t2c_data'
    )
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('table_type', sa.String(length=20), nullable=False),
    sa.Column('description_source', sa.Text(), nullable=True),
    sa.Column('description_manual', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=50), nullable=True),
    sa.Column('schema_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schema_id'], ['t2c_data.schemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_id', 'name', name='uq_tables_schema_name'),
    schema='t2c_data'
    )
    op.create_index(op.f('ix_t2c_data_tables_schema_hash'), 'tables', ['schema_hash'], unique=False, schema='t2c_data')
    op.create_table('columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('data_type', sa.String(length=200), nullable=False),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('is_nullable', sa.Boolean(), nullable=False),
    sa.Column('ordinal_position', sa.Integer(), nullable=False),
    sa.Column('description_source', sa.Text(), nullable=True),
    sa.Column('description_manual', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['t2c_data.tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'name', name='uq_columns_table_name'),
    schema='t2c_data'
    )
    op.create_table('lineage_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lineage_table_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('datasource_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['datasource_id'], ['t2c_data.data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lineage_table_id'], ['t2c_data.tables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['t2c_data.tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='t2c_data'
    )
    op.create_table('lineage_graph_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lineage_table_id', sa.Integer(), nullable=False),
    sa.Column('from_node_id', sa.Integer(), nullable=False),
    sa.Column('to_node_id', sa.Integer(), nullable=False),
    sa.Column('edge_type', sa.String(length=30), nullable=False),
    sa.Column('transform', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_node_id'], ['t2c_data.lineage_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lineage_table_id'], ['t2c_data.tables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['t2c_data.lineage_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='t2c_data'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineage_graph_edges', schema='t2c_data')
    op.drop_table('lineage_nodes', schema='t2c_data')
    op.drop_table('columns', schema='t2c_data')
    op.drop_index(op.f('ix_t2c_data_tables_schema_hash'), table_name='tables', schema='t2c_data')
    op.drop_table('tables', schema='t2c_data')
    op.drop_table('schemas', schema='t2c_data')
    op.drop_index(op.f('ix_t2c_data_scan_snapshots_entity_key'), table_name='scan_snapshots', schema='t2c_data')
    op.drop_index(op.f('ix_t2c_data_scan_snapshots_entity_hash'), table_name='scan_snapshots', schema='t2c_data')
    op.drop_table('scan_snapshots', schema='t2c_data')
    op.drop_index(op.f('ix_t2c_data_scan_diffs_entity_key'), table_name='scan_diffs', schema='t2c_data')
    op.drop_table('scan_diffs', schema='t2c_data')
    op.drop_table('user_role', schema='t2c_data')
    op.drop_index(op.f('ix_t2c_data_tag_assignments_datasource_id'), table_name='tag_assignments', schema='t2c_data')
    op.drop_table('tag_assignments', schema='t2c_data')
    op.drop_table('scan_runs', schema='t2c_data')
    op.drop_index(op.f('ix_t2c_data_lineage_edges_datasource_id'), table_name='lineage_edges', schema='t2c_data')
    op.drop_table('lineage_edges', schema='t2c_data')
    op.drop_index(op.f('ix_t2c_data_glossary_assignments_datasource_id'), table_name='glossary_assignments', schema='t2c_data')
    op.drop_table('glossary_assignments', schema='t2c_data')
    op.drop_table('databases', schema='t2c_data')
    op.drop_table('audit_logs', schema='t2c_data')
    op.drop_table('users', schema='t2c_data')
    op.drop_table('tags', schema='t2c_data')
    op.drop_table('roles', schema='t2c_data')
    op.drop_table('lineage_processes', schema='t2c_data')
    op.drop_table('glossary_terms', schema='t2c_data')
    op.drop_table('data_sources', schema='t2c_data')
    # ### end Alembic commands ###
